### ISSUE TITLE
Add support to no validate ca

### ISSUE THREAD

**Issue by carlososiel** [maxlaverse/kubernetes-cli-plugin#1]
I use a not trusted ca certificate, and I need to skip certificate validation when in pipeline specified a caCertificate. Maybe that exist, but i don't see in documentation.

**Comment by maxlaverse** [comment]
Hi @carlososiel 
I'm not sure to understand what you mean. 
The Kubernetes authority is generated on the cluster installation and is not trusted in the way https certificates are trusted for example.

Putting the caCertificate should always work, if it's the real one.
You can skip this verification by not providing one.

Can give me more information ?

**Comment by carlososiel** [comment]
I try without ca and work for me. Thanks
